[package]
name = "trait_hasher"
version = "0.1.0"
edition = "2021"

[dependencies]
autozig = { path = "../.." }

[build-dependencies]
autozig = { path = "../.." }
autozig-build = { path = "../../gen/build" }