[package]
name = "autozig-demo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
autozig = { path = "..", version = "0.1.0" }

[build-dependencies]
autozig-build = { path = "../gen/build", version = "0.1.0" }
anyhow = "1.0"